name: Manual Trigger with Parameters

on:
  workflow_dispatch:
    inputs:
      
      name:
        description: 'Name of the person to greet'
        required: true
        type: string

      gretting:
        description: 'Greeting message'
        required: true
        type: string

      data: 
        description: 'Based64 encoded data of a file'
        required: false
        type: string

jobs: 
  greet:
    runs-on: ubuntu-latest
    steps:

      - name: Decode File Content
        run: | 
          echo "${{ inputs.data}}" | base64 --decode > ./decoded_file.txt

      - name: Display Greeting
        run: |
          echo "${{inputs.gretting}}, ${{ inputs.name }}"

      - name: Display File Content
        run: |
          echo "Content of the file : "
          cat ./decoded_file.txt